# version: '3.9'

# services:
#   web:
#     image: trijal/stude-v2:latest
#     container_name: fastapi_stude
#     ports:
#       - "8000:8000"
#     env_file:
#       - ../.env
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo
#     container_name: mongo_stude
#     restart: always
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_DATABASE: studE

version: "3.9"

volumes:
  prom_data:
  grafana_data:

networks:
  studenet:

services:
  # ──────────── FastAPI ────────────
  web:
    image: trijal/stude-v2:latest       
    container_name: fastapi_stude
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on: [mongo]
    networks: [studenet]

  # ──────────── MongoDB ────────────
  mongo:
    image: mongo
    container_name: mongo_stude
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: studE
    networks: [studenet]

  # ──────────── Prometheus ────────────
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks: [studenet]

  # ──────────── Node Exporter (host metrics) ────────────
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    network_mode: host          
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped

  # ──────────── Grafana ────────────
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on: [prometheus]
    networks: [studenet]
