version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_stude
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_stude
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: studE
