name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest image
      run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/stude-v2:latest

    - name: Stop and remove old container
      run: |
        sudo docker-compose -f /home/ubuntu/studE-v2/docker-compose.yml down || true

    - name: Deploy new container
      run: |
        cd /home/ubuntu/studE-v2
        sudo docker-compose -f docker-compose.yml up -d
