name: Docker Deploy to EC2

on:
  push:
    branches: [ main ]  # or your preferred branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: trijal18/stude-app
      CONTAINER_NAME: stude-app
      CONTAINER_PORT: 8000

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .

    - name: Copy .env to EC2 (if needed)
      run: echo "$ENV_FILE" > .env
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker rm -f $CONTAINER_NAME || true
          cd ~/studE-v2 || git clone https://github.com/trijal18/studE-v2 && cd studE-v2
          git pull origin main
          docker build -t $IMAGE_NAME .
          docker run --env-file .env -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME
